### Librerías

In [1]:
#librerias
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey
from sqlalchemy import inspect

### Conexión

In [2]:
#Conectar el motor al archivo de la base de datos a usar
engine = create_engine('sqlite:///chinook.db')
engine

Engine(sqlite:///chinook.db)

### Extract

In [3]:
metadata = MetaData()
metadata.create_all(engine) 
inspector = inspect(engine) 
inspector.get_columns('artists')
inspector.get_columns('albums')
inspector.get_columns('invoice_items')
inspector.get_columns('invoices')
inspector.get_columns('customers')
inspector.get_columns('employees')
inspector.get_columns('genres')
inspector.get_columns('playlists')

[{'name': 'PlaylistId',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'autoincrement': 'auto',
  'primary_key': 1},
 {'name': 'Name',
  'type': NVARCHAR(length=120),
  'nullable': True,
  'default': None,
  'autoincrement': 'auto',
  'primary_key': 0}]

* ***invoice -> dim_location***

In [4]:
#invoice -> dim_location
import pandas as pd
dim_location = pd.read_sql_query("""SELECT 
invoices.InvoiceId,
invoices.InvoiceDate,
invoices.BillingAddress,
invoices.BillingCity,
    CASE 
    WHEN invoices.BillingState IS NULL THEN "N/A"
    ELSE invoices.BillingState
    END AS BillingState,
invoices.BillingCountry,
    CASE 
    WHEN invoices.BillingPostalCode  IS NULL THEN "N/A"
    ELSE invoices.BillingPostalCode
    END AS BillingPostalCode,
invoices.Total
FROM 
    invoices;""", con=engine.connect())

* ***albums -> dim_albums***

In [5]:
#albums -> dim_albums
import pandas as pd
dim_albums = pd.read_sql_query("""SELECT 
    albums.AlbumId,
    albums.Title
 FROM albums;
""", con=engine.connect())

* ***artists -> dim_artist***

In [6]:
#artists -> dim_artist
import pandas as pd
dim_artist = pd.read_sql_query(""" 
SELECT 
    artists.ArtistId,
    artists.Name
FROM artists;""", con=engine.connect())

* ***customers -> dim_customers***

In [7]:
#customers -> dim_customers
import pandas as pd
dim_customers = pd.read_sql_query("""SELECT 
    customers.CustomerId,
    customers.FirstName,
    customers.LastName,
    CASE 
    WHEN customers.Company IS NULL THEN "N/A"
    ELSE customers.Company
    END AS Company,
    customers.Address,
    customers.City,
    CASE 
    WHEN customers.State IS NULL THEN "N/A"
    ELSE customers.State
    END AS State,
    customers.Country,
    CASE 
    WHEN customers.PostalCode IS NULL THEN "N/A"
    ELSE customers.PostalCode
    END AS PostalCode,
    CASE 
    WHEN customers.Phone IS NULL THEN "N/A"
    ELSE customers.Phone
    END AS Phone,
    CASE 
    WHEN customers.Fax IS NULL THEN "N/A"
    ELSE customers.Fax
    END AS Fax,
    customers.Email
FROM customers;""", con=engine.connect())

* ***employees -> dim_employee***

In [8]:
#employees -> dim_employee
import pandas as pd
dim_employee = pd.read_sql_query("""SELECT 
    employees.EmployeeId,
    employees.LastName,
    employees.FirstName,
    employees.Title,
    employees.BirthDate,
    employees.HireDate,
    employees.Address,
    employees.City,
    employees.State,
    employees.Country,
    employees.PostalCode,
    employees.Phone,
    employees.Fax,
    employees.Email
FROM employees;""", con=engine.connect())

* ***genres -> dim_genres***

In [9]:
#genres -> dim_genres
import pandas as pd
dim_genres = pd.read_sql_query("""SELECT 
    genres.GenreId,
    genres.Name
FROM genres;
""", con=engine.connect())

* ***invoce_items -> dim_invoice_items***

In [10]:
#invoce_items -> dim_invoice_items
import pandas as pd
dim_invoice_items = pd.read_sql_query("""SELECT 
    invoice_items.InvoiceLineId,
    invoice_items.UnitPrice,
    invoice_items.Quantity
FROM invoice_items;

""", con=engine.connect())

* ***playlists  ->  dim_playlists***

In [11]:
#playlists  ->  dim_playlists
import pandas as pd
dim_playlists = pd.read_sql_query("""SELECT 
    playlists.PlaylistId,
    playlists.Name
FROM playlists;""", con=engine.connect())

### Load

In [12]:
#Exportar el archivo en un formato a su elección.

dim_location.to_csv('dataframedim_location.csv')
dim_albums.to_csv('dataframedim_albums.csv')
dim_artist.to_csv('dataframedim_artist.csv')
dim_customers.to_csv('dataframedim_customers.csv')
dim_employee.to_csv('dataframedim_employee.csv')
dim_genres.to_csv('dataframedim_genres.csv')
dim_invoice_items.to_csv('dataframedim_invoice_items.csv')
dim_playlists.to_csv('dataframedim_playlists.csv')